const ERROR_STATUS_MAP = {
   "Invalid id": 400,
    "Category name is required": 400,
    "Category already exists": 400,
    "Category not found": 404,
    "Ingredient not found": 404,
    "Ingredient name is required!": 400,
    "Ingredient already exists!": 400,
    "Unit must be ml,gr or pcs": 400,
    "Stock must be number and grater than or equal to 0": 400,
    "Cannot delete ingredient because it is used in recipes": 409,
    "Addon name is required!": 400,
    "Addon already exists!": 400,
    "Addon not found!": 404,
    "Price must be number and grater than or equal to 0": 400,
    "Addon ingredient not found!": 404,
    "Amount must be a number and greater than 0": 400,
    "Beverage name is required!": 400,
    "Beverage already exists!": 400,
    "Base price must be a number greater than or equal to 0": 400,
    "Invalid category id": 400,
    "Beverage not found": 404,
    "Invalid beverage id": 400,
    "Invalid ingredient id": 400,
    "Ingredient already exists in recipe": 400,
    "Recipe ingredient not found": 404,
    "Ingredient not found in recipe": 404,
    "Invalid addon id": 400,
    "Addon already exists in beverage": 400,
    "Addon not found in beverage": 404,
}

export const getStatusCode = (message) => {
return ERROR_STATUS_MAP[message] || 500
}
